package cache

import (
	"bytes"
	"testing"
	"time"

	"github.com/google/uuid"
)

// fixedTime is a timestamp that survives a JSON round-trip byte-for-byte
// (UTC, no monotonic clock reading).
func fixedTime() time.Time {
	return time.Date(2026, 10, 7, 12, 30, 45, 123456789, time.UTC)
}

// sampleSession returns a fully populated session, including a non-empty
// already-shown list to exercise nested collections.
func sampleSession() *GameSession {
	return &GameSession{
		SessionID:  "550e8400-e29b-41d4-a716-446655440000",
		Nickname:   "carlos",
		Difficulty: "hard",
		Hearts:     2,
		Score:      1234,
		ShownIDs:   []int64{7, 3, 42},
		CreatedAt:  fixedTime(),
	}
}

// assertSessionsEqual compares every field, using Equal() for the timestamp.
func assertSessionsEqual(t *testing.T, want, got *GameSession) {
	t.Helper()
	if got == nil {
		t.Fatal("session is nil")
	}
	if got.SessionID != want.SessionID {
		t.Errorf("SessionID = %q, want %q", got.SessionID, want.SessionID)
	}
	if got.Nickname != want.Nickname {
		t.Errorf("Nickname = %q, want %q", got.Nickname, want.Nickname)
	}
	if got.Difficulty != want.Difficulty {
		t.Errorf("Difficulty = %q, want %q", got.Difficulty, want.Difficulty)
	}
	if got.Hearts != want.Hearts {
		t.Errorf("Hearts = %d, want %d", got.Hearts, want.Hearts)
	}
	if got.Score != want.Score {
		t.Errorf("Score = %d, want %d", got.Score, want.Score)
	}
	if len(got.ShownIDs) != len(want.ShownIDs) {
		t.Errorf("ShownIDs = %v, want %v", got.ShownIDs, want.ShownIDs)
	} else {
		for i := range want.ShownIDs {
			if got.ShownIDs[i] != want.ShownIDs[i] {
				t.Errorf("ShownIDs[%d] = %d, want %d", i, got.ShownIDs[i], want.ShownIDs[i])
			}
		}
	}
	if !got.CreatedAt.Equal(want.CreatedAt) {
		t.Errorf("CreatedAt = %v, want %v", got.CreatedAt, want.CreatedAt)
	}
}

// TestNewGameSessionInitializesFields covers R5.1: every mandated field is
// present with its required initial value and a server-generated Session_ID.
func TestNewGameSessionInitializesFields(t *testing.T) {
	session := NewGameSession("carlos", "easy", fixedTime())

	if session.SessionID == "" {
		t.Error("Session_ID must be generated by the server")
	}
	if _, err := uuid.Parse(session.SessionID); err != nil {
		t.Errorf("Session_ID is not a valid UUID: %v", err)
	}
	if session.Nickname != "carlos" {
		t.Errorf("Nickname = %q, want carlos", session.Nickname)
	}
	if session.Difficulty != "easy" {
		t.Errorf("Difficulty = %q, want easy", session.Difficulty)
	}
	if InitialHearts != 3 {
		t.Errorf("InitialHearts = %d, the spec requires 3", InitialHearts)
	}
	if session.Hearts != 3 {
		t.Errorf("Hearts = %d, want 3", session.Hearts)
	}
	if session.Score != 0 {
		t.Errorf("Score = %d, want 0", session.Score)
	}
	if session.ShownIDs == nil || len(session.ShownIDs) != 0 {
		t.Errorf("ShownIDs = %v, want an empty non-nil list", session.ShownIDs)
	}
	if !session.CreatedAt.Equal(fixedTime()) {
		t.Errorf("CreatedAt = %v, want %v", session.CreatedAt, fixedTime())
	}
}

// TestSerializeIsDeterministic covers R20.1: the same state always serializes
// to identical bytes, including after a round-trip.
func TestSerializeIsDeterministic(t *testing.T) {
	first, err := Serialize(sampleSession())
	if err != nil {
		t.Fatalf("Serialize() failed: %v", err)
	}
	second, err := Serialize(sampleSession())
	if err != nil {
		t.Fatalf("Serialize() failed: %v", err)
	}
	if !bytes.Equal(first, second) {
		t.Errorf("serializing the same state twice differs:\n%s\n%s", first, second)
	}

	decoded, err := Deserialize(first)
	if err != nil {
		t.Fatalf("Deserialize() failed: %v", err)
	}
	third, err := Serialize(decoded)
	if err != nil {
		t.Fatalf("Serialize() after round-trip failed: %v", err)
	}
	if !bytes.Equal(first, third) {
		t.Errorf("serialize -> deserialize -> serialize changed the bytes:\n%s\n%s", first, third)
	}
}

// TestRoundTripPreservesEveryField covers R20.2 and R20.3: all fields,
// including the nested already-shown list, survive serialization unchanged.
func TestRoundTripPreservesEveryField(t *testing.T) {
	original := sampleSession()

	data, err := Serialize(original)
	if err != nil {
		t.Fatalf("Serialize() failed: %v", err)
	}
	restored, err := Deserialize(data)
	if err != nil {
		t.Fatalf("Deserialize() failed: %v", err)
	}

	assertSessionsEqual(t, original, restored)
}

// TestSerializeFailureWritesNothing covers R20.4: a serialization failure
// returns an error and no bytes, so nothing partial can reach the Cache.
func TestSerializeFailureWritesNothing(t *testing.T) {
	data, err := Serialize(nil)
	if err == nil {
		t.Fatal("Serialize(nil) should fail")
	}
	if data != nil {
		t.Errorf("Serialize(nil) returned bytes on failure: %q", data)
	}
}

// TestDeserializeRejectsCorruptState covers R20.5: corrupt stored bytes
// produce an error and never a partial Game_Session.
func TestDeserializeRejectsCorruptState(t *testing.T) {
	session, err := Deserialize([]byte(`{"session_id": "half-written`))
	if err == nil {
		t.Fatal("Deserialize() of corrupt JSON should fail")
	}
	if session != nil {
		t.Errorf("Deserialize() returned a partial object on failure: %+v", session)
	}
}
